---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE
  labels:
    team: $TEAM
    svc: $SERVICE
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    svc: $SERVICE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE
  labels:
    team: $TEAM
    svc: $SERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: $SERVICE
  template:
    metadata:
      labels:
        svc: $SERVICE
        team: $TEAM
        tags.datadoghq.com/env: "$APP_ENV"
        tags.datadoghq.com/service: "$SERVICE"
        tags.datadoghq.com/version: "$VERSION"
      annotations:
        ad.datadoghq.com/tags: '{"team": "$TEAM", "app_name": "$APP_NAME"}'

    spec:
      containers:
        - name : $SERVICE
          image: $SERVICE_IMAGE
          env:
            - name: SERVICE
              value: $SERVICE
            - name: APP_ENV
              value: "$APP_ENV"
            - name: DB_HOST
              value: "$DB_HOST"
            - name: DB_PORT
              value: "$DB_PORT"
            - name: DB_USER
              value: "$DB_USER"
            - name: DB_PASS
              value: "$DB_PASS"
            - name: DB_NAME
              value: "$DB_NAME"
            - name: DB_SCHEMA
              value: "$DB_SCHEMA"
            - name: HTTP_PORT
              value: "$HTTP_PORT"
          ports:
            - containerPort: 80
          resources:
            limits  : {cpu: "$LIMITS_CPU", memory: "$LIMITS_MEMORY"}
            requests: {cpu: "$REQUESTS_CPU", memory: "$REQUESTS_MEMORY"}
      imagePullSecrets:
        - name: $IMAGE_PULL_SECRET
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: $SERVICE
  labels: { svc: $SERVICE, team: $TEAM}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $SERVICE
  minReplicas: $MIN_REPLICAS
  maxReplicas: $MAX_REPLICAS
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: $CPU_AVERAGE_UTILIZATION
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 200Mi
